defmodule BulkUpsertDemo.Repo do
  use Ecto.Repo,
    otp_app: :bulk_upsert,
    adapter: Ecto.Adapters.Postgres

  @doc """
  Extend `insert_all/3` to autogenerate the current insert timestamp when performing bulk insert
  operations. (This is the custom `:insert_all_function_atom` recipe shown in the README.)
  """
  def insert_all_with_autogenerated_timestamps(schema_module, entries, opts \\ [])

  def insert_all_with_autogenerated_timestamps(schema_module, entries, opts)
      when is_atom(schema_module) do
    timestamp_placeholders =
      [inserted_at: DateTime.utc_now()]
      |> Map.new()
      # Reject timestamp fields that are not defined in the given `schema_module`
      |> Map.reject(fn {field, _value} -> schema_module.__schema__(:type, field) |> is_nil() end)

    if Enum.empty?(timestamp_placeholders) do
      insert_all(schema_module, entries, opts)
    else
      timestamp_placeholder_attrs =
        Map.new(timestamp_placeholders, fn {field, _value} -> {field, {:placeholder, field}} end)

      entries = Enum.map(entries, &Map.merge(&1, timestamp_placeholder_attrs))

      placeholders = Keyword.get(opts, :placeholders, %{}) |> Map.merge(timestamp_placeholders)
      opts = Keyword.put(opts, :placeholders, placeholders)

      insert_all(schema_module, entries, opts)
    end
  end

  # String sources (e.g. `many_to_many` join tables) have no schema to inspect, so insert as-is
  def insert_all_with_autogenerated_timestamps(source, entries, opts) when is_binary(source) do
    insert_all(source, entries, opts)
  end
end
